### ISSUE TITLE
lo_url_get_port(): address sanitizer issue

### ISSUE THREAD

**Issue by uliss** [radarsat1/liblo#128]
this simple test program compiled with flags `clang -fno-omit-frame-pointer -fsanitize=address -llo test_lo_asan.c`

liblo version: 0.30

```C
#include <lo/lo.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

int main(int argc, char* argv[]) {
	if (argc != 2) { fprintf(stderr, "Usage: %s URL\n", argv[0]); return 1; }
	char* p = lo_url_get_port(argv[1]);
	if (p) {
		strlen(p);
		printf("port: %s\n", p);
		free(p);
	}
	return 0;
}
```

and runned with args `./a.out osc://127.0.0.1`

produces this failure:

```
==59683==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000000ff at pc 0x00010149d95d bp 0x7ffeef0929f0 sp 0x7ffeef092198
READ of size 16 at 0x6020000000ff thread T0
    #0 0x10149d95c in wrap_strlen (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x1595c)
Provided dSYM: [/Users/serge/work/music/pure-data/build/mac/asan/32/./a.out.dSYM/Contents/Resources/DWARF/a.out] does not match symbol owner 0x7fa801509300
    #1 0x100b6ddec in main (a.out:x86_64+0x100000dec)
    #2 0x7fff5778f3d4 in start (libdyld.dylib:x86_64+0x163d4)

0x6020000000ff is located 0 bytes to the right of 15-byte region [0x6020000000f0,0x6020000000ff)
allocated by thread T0 here:
    #0 0x1014e69f3 in wrap_malloc (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x5e9f3)
    #1 0x100b741a0 in lo_url_get_port (liblo.7.dylib:x86_64+0x11a0)
    #2 0x100b6ddd4 in main (a.out:x86_64+0x100000dd4)
    #3 0x7fff5778f3d4 in start (libdyld.dylib:x86_64+0x163d4)

SUMMARY: AddressSanitizer: heap-buffer-overflow (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x1595c) in wrap_strlen
Shadow bytes around the buggy address:
  0x1c03ffffffc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c03ffffffd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c03ffffffe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c03fffffff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c0400000000: fa fa fd fd fa fa fd fd fa fa 00 00 fa fa 00 05
=>0x1c0400000010: fa fa 00 04 fa fa 00 00 fa fa 00 06 fa fa 00[07]
  0x1c0400000020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==59683==ABORTING
Abort trap: 6
```

As I suggest the issues is:
- https://github.com/radarsat1/liblo/blob/fa7adc96a2f987a156cd5717a2235532b3b08cbe/src/address.c#L412 malloc string should be `strlen()+1` for terminating zero in case of full match

but I'm not shure about it

**Comment by uliss** [comment]
Closing, not in release, but fixed in d56d120ec3affc3e67f5d641bdf9ce78100db52a
